apiVersion: v1
kind: Service
metadata:
  name: httpd-service-datacenter
spec:
  type: NodePort
  selector:
    app: httpd-deployment-datacenter
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
