apiVersion: v1
kind: Pod
metadata:
  name: secret-datacenter
spec:
  containers:
  - name: secret-container-datacenter
    image: ubuntu:latest
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: secret-mount
      mountPath: "/opt/apps"
  volumes:
  - name: secret-mount
    secret:
      secretName: news
